import Content from "@/components/Content";
import Copyright from "@/components/Copyright";
import Header from "@/components/Header";
import Navigator from "@/components/Navigator";
import theme from "@/config/theme";
import { Paper } from "@mui/material";
import Box from "@mui/material/Box";
import CssBaseline from "@mui/material/CssBaseline";
import useMediaQuery from "@mui/material/useMediaQuery";
import Head from "next/head";
import * as React from "react";

const drawerWidth = 256;

export default function Home() {
  const [mobileOpen, setMobileOpen] = React.useState(false);
  const isSmUp = useMediaQuery(theme.breakpoints.up("sm"));

  const handleDrawerToggle = () => {
    setMobileOpen(!mobileOpen);
  };
  return (
    <>
      <Head>
        <title>Student Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CssBaseline />
        <Paper sx={{ display: "flex", minHeight: "100vh", width: "100vw" }}>
          <Box
            component="nav"
            sx={{ width: { sm: drawerWidth }, flexShrink: { sm: 0 } }}
          >
            {isSmUp ? null : (
              <Navigator
                PaperProps={{ style: { width: drawerWidth } }}
                variant="temporary"
                open={mobileOpen}
                onClose={handleDrawerToggle}
              />
            )}

            <Navigator
              PaperProps={{ style: { width: drawerWidth } }}
              sx={{ display: { sm: "block", xs: "none" } }}
            />
          </Box>
          <Box sx={{ width: "100vw" }}>
            <Header onDrawerToggle={handleDrawerToggle} />
            <Box
              component="main"
              sx={{
                width: "100%",
                py: 6,
                px: 2,
                pr: 4,
                bgcolor: "#eaeff1",
              }}
            >
              <Content />
            </Box>
            <Box component="footer" sx={{ p: 2, bgcolor: "#eaeff1" }}>
              <Copyright />
            </Box>
          </Box>
        </Paper>
      </main>
    </>
  );
}
